### PR TITLE
Improved logging capabilities using standard python

### PR DESCRIPTION
**Pull request by mysten-labs-charles-murphy**
Much of this code exists in 3rd party libraries. Re-inventing of the wheel is deliberate due to requirement of @mystenmark to avoid use of 3rd party libraries.

The code here generates log files to trace the function invocations of important functions within the codebase. At the moment, that is the parse-output and subprocess functions.

### CODE REVIEW

**Comment by mystenmark** [comment]
I think we should use a single log file. It will be simpler for operators to submit, and it will be helpful to use since it will not obscure the ordering of events.

**Comment by mysten-labs-charles-murphy** [comment]
> I think we should use a single log file. It will be simpler for operators to submit, and it will be helpful to use since it will not obscure the ordering of events.

Feel free to make the change and then merge. It's EOD for me. I wanted you to see the impact of that change before committing to it.

While I agree with your thought process, when you see the file output with your eyes, you might change your mind.

Sui-doctor.log serves as a good unified general log. Those other logs are JSON structured and are aimed digging into the input/output of a specific call.

Ultimately, it's your choice but I think you should look with your eyes so that it's a practical decision as supposed to a theoretical one.

**Review by tharbert — APPROVED** [review]

**Comment by mysten-labs-charles-murphy** [comment]
Screenshot 2023-05-01 at 12 18 38 PM

See an example of what the invocation log file looks like. As you can see it is json-formatted. It may not be suitable to mix in with raw logging.

@mystenmark @tharbert Let me know if you still think the file outputs should be combined.

**Comment by mysten-labs-charles-murphy** [comment]
@tharbert and I discussed this PR earlier today (UK time). We decided to merge the PR as-is because it is very easy for @mystenmark to spin another PR to update the log file locations if desired.

@mystenmark, there's no objection if you decide to update the log file locations. We just felt that since the logging in the *.json.log files are structured, it made more sense (initially, at least) to have them separate. This allows automation on the *.json.log files (i.e. chatgpt or a script for post-analysis purposes.

Please update in a new PR if you feel strongly otherwise.

**Pull request merged**
